config/routes.rb
Rails.application.routes.draw do
  root to: 'counties#index'

  resources :counties

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caseload.rb
class Caseload < ApplicationRecord
  belongs_to :county
end

app/models/county.rb
class County < ApplicationRecord
  has_many :caseloads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  def index
    @counties = County.all
  end

  def show
    @county = County.find(params[:id])

    if @county.name == 'New York City' # Hack -- only NYC to save $$$
      FetchCases.call(county: @county)
    end
    @cases_by_date = @county.caseloads.order('date ASC').pluck(:date, :cases)

    @new_cases_by_date = (0...@cases_by_date.size).map do |index|
      new_cases(@cases_by_date, index)
    end
  end

  private

  def new_cases(dates_and_cases, index)
    date_case = dates_and_cases[index].dup

    if index == 0
      date_case
    else
      date_case[1] = cases_delta(dates_and_cases, index) # TODO: fix primitive obsession
      date_case
    end
  end

  def cases_delta(dates_and_cases, index)
    dates_and_cases[index][1] - dates_and_cases[index - 1][1]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/index.html.erb
<h1>Check out these counties</h1>
<ul>
  <% @counties.each do |county| %>
      <li>
        <%= link_to(county.name, county_path(county)) %>
      </li>
  <% end %>
</ul>

app/views/counties/show.html.erb
<h1><%= @county.name %></h1>

<img src="https://www.thesprucepets.com/thmb/kV_cfc9P4QWe-klxZ8y--awxvY4=/960x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/adorable-white-pomeranian-puppy-spitz-921029690-5c8be25d46e0fb000172effe.jpg">

<h3>Total Cases</h3>
<%= line_chart @cases_by_date %>

<h3>New Cases</h3>
<%= column_chart @new_cases_by_date %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coviz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>